import click
import uuid
from job_storage import init_db, add_job, current_time

@click.group()
def cli():
    """queuectl - Job Queue CLI"""
    pass

@cli.command()
def init():
    """Initialize database (run on first setup)."""
    init_db()
    click.echo("Database initialized.")

@cli.command()
@click.option('--id', 'job_id', default=None, help='Job ID (optional, autogenerated if omitted)')
@click.option('--command', required=True, help='Shell command to run (e.g., "echo hello")')
@click.option('--max-retries', default=3, type=int, help='Max retries allowed (default 3)')
def enqueue(job_id, command, max_retries):
    """Add a new job to the queue."""
    if job_id is None:
        job_id = str(uuid.uuid4())
    now = current_time()
    job_data = {
        'id': job_id,
        'command': command,
        'state': 'pending',
        'attempts': 0,
        'max_retries': max_retries,
        'created_at': now,
        'updated_at': now
    }
    try:
        add_job(job_data)
        click.echo(f"Enqueued job: {job_data['id']}")
    except Exception as e:
        click.echo(f"Failed to enqueue job: {e}", err=True)

if __name__ == "__main__":
    cli()
